### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by grandmotivator** [montelibero-org/shareholders#3]
Подключить какой нибудь UI для приятного внешнего вида, например:

- https://www.slant.co/topics/3946/~best-bootstrap-alternatives
- https://getbootstrap.com/docs/4.0/getting-started/introduction/
- https://material-ui.com
- https://jqueryui.com
- или другие похожие простые аналоги

Предпочтительно взять такой UI чтобы не пришлось компилировать и билдить изменения кода.

**Comment by cblp** [comment]
done via #13
