### ISSUE TITLE
Switch to TypeScript

### ISSUE THREAD

**Issue by cblp** [montelibero-org/shareholders#4]
https://webpack.js.org/guides/typescript/

**Comment by grandmotivator** [comment]
Если этот вариант потребует компилировать и билдить код, то лучше избежать подобного, так как становится сложнее работать с кодом и контрибьюторам потребуется устанавливать дополнительное ПО для работы с сайтом.

**Comment by cblp** [comment]
Да, это минус.

Плюс — легче код писать и читать.

Надо попробовать и взвесить.

**Comment by cblp** [comment]
There are a few options to write TypeScript without installing tools, compiling at client side:
- https://github.com/niutech/typescript-compile
- https://github.com/basarat/typescript-script

**Comment by cblp** [comment]
The former — niutech/typescript-compile — is dramatically outdated.

The latter — basarat/typescript-script — works on a website, such as Github Pages, but does not work locally (CORS forbids loading files as resources inside scripts, hence TS fails to load modules).

Failing to work offline is a minus too.

**Comment by cblp** [comment]
I can try to write the whole program in a single file. Hello to #2

**Comment by cblp** [comment]
Formally switched. Now fixing type errors.

**Comment by cblp** [comment]
done
