### ISSUE TITLE
Генерация транзакции на изменение списка подписантов

### ISSUE THREAD

**Issue by grandmotivator** [montelibero-org/shareholders#8]
Вывести предполагаемый порог голосов для аккаунтов фонда и подпроектов, и у каждого мажоритарного акционера рассчитанное количество голосов исходя из его количества токенов.

Сгенерировать транзакцию на изменение списка подписантов, учитывая текущий список подписантов (добавляя новых, меняя значения голосов у текущих, удаляя тех кто должен выйти из списка подписантов). Предоставить ссылку на просмотр транзакции в laboratory.stellar.org чтобы ее можно было подписать.

**Comment by cblp** [comment]
duplicate of #7
